import json
import os

def generate_json():
    problem_id = 1332
    title = "Remove Palindromic Subsequences"
    difficulty = "EASY"
    marks = 10

    html_description = """<h3>1332. Remove Palindromic Subsequences</h3>
<p>You are given a string <code>s</code> consisting <strong>only</strong> of letters <code>'a'</code> and <code>'b'</code>. In a single step you can remove one <strong>palindromic subsequence</strong> from <code>s</code>.</p>

<p>Return <em>the <strong>minimum</strong> number of steps to make the given string empty</em>.</p>

<p>A string is a <strong>subsequence</strong> of a given string if it is generated by deleting zero or more characters from the given string without changing the order of the remaining characters.</p>

<p>A subsequence is <strong>palindromic</strong> if it reads the same backward as forward.</p>

<p>&nbsp;</p>
<p><strong class="example">Example 1:</strong></p>
<pre><strong>Input:</strong> s = "ababa"
<strong>Output:</strong> 1
<strong>Explanation:</strong> s is already a palindrome, so its entire subsequence can be removed in a single step.
</pre>

<p><strong class="example">Example 2:</strong></p>
<pre><strong>Input:</strong> s = "abb"
<strong>Output:</strong> 2
<strong>Explanation:</strong> "<strong>a</strong>bb" -> "<strong>bb</strong>" -> "". 
Remove palindromic subsequence "a" then "bb".
</pre>

<p><strong class="example">Example 3:</strong></p>
<pre><strong>Input:</strong> s = "baabb"
<strong>Output:</strong> 2
<strong>Explanation:</strong> "<strong>baa</strong>b<strong>b</strong>" -> "<strong>b</strong>b" -> "". 
Remove palindromic subsequence "baab" then "b".
</pre>

<p>&nbsp;</p>
<p><strong>Constraints:</strong></p>
<ul>
	<li><code>1 &lt;= s.length &lt;= 1000</code></li>
	<li><code>s[i]</code> is either <code>'a'</code> or <code>'b'</code>.</li>
</ul>"""

    input_format = "A string `s` enclosed in quotes."
    output_format = "An integer representing the minimum steps."

    constraints = [
        "1 <= s.length <= 1000",
        "s consists of 'a' and 'b'"
    ]

    explanation = """To minimize removals for a string of 'a' and 'b':
1. If the string is already a palindrome, it can be removed in one step.
2. If the string is not a palindrome, we can always remove all 'a's in one step (since a string of the same character is a palindrome) and all 'b's in another step.
3. Therefore, the answer is either 1 or 2. Empty string is not possible based on constraints (length >= 1)."""

    answer = """class Solution:
    def removePalindromeSub(self, s: str) -> int:
        return 1 if s == s[::-1] else 2"""

    boilerplate = {
        "python": """import sys

class Solution:
    def removePalindromeSub(self, s: str) -> int:
        # User logic here
        return 0

if __name__ == '__main__':
    raw = sys.stdin.read().strip()
    if raw.startswith('"') and raw.endswith('"'): raw = raw[1:-1]
    sol = Solution()
    print(sol.removePalindromeSub(raw))""",
        "cpp": """#include <iostream>
#include <string>
#include <algorithm>

using namespace std;

class Solution {
public:
    int removePalindromeSub(string s) {
        // User logic here
        return 0;
    }
};

int main() {
    printf("1\\n");
    return 0;
}""",
        "java": """import java.util.*;

class Solution {
    public int removePalindromeSub(String s) {
        // User logic here
        return 0;
    }
}

public class Main {
    public static void main(String[] args) {
        System.out.println(1);
    }
}""",
        "javascript": """/**
 * @param {string} s
 * @return {number}
 */
var removePalindromeSub = function(s) {
    // User logic here
};

const fs = require('fs');
const input = fs.readFileSync(0, 'utf8').trim().replace(/"/g, '');
if (input) {
    console.log(removePalindromeSub(input));
}""",
        "c": """#include <stdio.h>
#include <string.h>

int removePalindromeSub(char* s) {
    // User logic here
    return 0;
}

int main() {
    printf("1\\n");
    return 0;
}"""
    }

    def solve(s):
        if not s: return 0
        return 1 if s == s[::-1] else 2

    test_cases_data = ["ababa", "abb", "baabb", "a", "b", "aa", "ab", "aaaabbbb", "ababa", "baabaa"]

    test_cases = []
    for i, s in enumerate(test_cases_data):
        inp = f'"{s}"'
        out = str(solve(s))
        is_sample = i < 3
        test_cases.append({"input": inp, "expected_output": out, "is_sample": is_sample})

    data = {
        "question_id": problem_id,
        "question_text": html_description,
        "difficulty": difficulty,
        "marks": marks,
        "input_format": input_format,
        "output_format": output_format,
        "constraints": constraints,
        "explanation": explanation,
        "answer": answer,
        "boilerplate": boilerplate,
        "test_cases": test_cases,
        "metadata": {"time_limit_ms": 1000, "memory_limit_mb": 256, "allowed_languages": ["python", "cpp", "java", "javascript", "c"]},
        "topics": ["String", "Greedy"],
        "companyIndex": 0
    }

    output_path = f"1301-1500/{problem_id}_{title.replace(' ', '_')}.json"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding='utf-8') as f:
        json.dump(data, f, indent=2)
    print(f"Generated {output_path}")

if __name__ == "__main__":
    generate_json()
